[font]
normal = { family = "Iosevka Nerd Font" }
size = 10

[colors.primary]
background = "#2e3440"
foreground = "#e8e3e8"
dim_foreground = "#d8d3e8"
bright_foreground = "#f8e3f8"

[colors.cursor]
text = "#000000"
cursor = "#e8e3e8"

[colors.search.matches]
foreground = "#373737"
background = "#e8e3e8"

[colors.search.focused_match]
foreground = "#e8e3e8"
background = "#82c0ec"

[colors.footer_bar]
foreground = "#000000"
background = "#ffffff"

# [colors.hints.start]
# foreground = "#0f0f0f"
# background = "#d8d38c"
#
# [colors.hints.end]
# foreground = "#0f0f0f"
# background = "#f9f9f9"

[colors.selection]
text = "#e8e3e8"
background = "#82c0ec"

[colors.normal]
black = "#535c6e"
red = "#e85397"
green = "#1a1d1e"
yellow = "#f98acf"
blue = "#9f89be"
magenta = "#906da1"
cyan = "#8a9ad5"
white = "#ffffff"

# [colors.bright]
# inherit = true
#
# [colors.dim]
# inherit = true

[[colors.indexed_colors]]
index = 16
color = "#82c0ec"

[[colors.indexed_colors]]
index = 17
color = "#ffffff"
